/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ImportsIndexRouteImport } from './routes/imports.index'
import { Route as ArchiveIndexRouteImport } from './routes/archive.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ActivityIndexRouteImport } from './routes/activity.index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ReceiptsNewRouteImport } from './routes/receipts.new'
import { Route as FinanceReceiptUploadRouteImport } from './routes/finance.receipt-upload'
import { Route as FinanceInstallmentsRouteImport } from './routes/finance.installments'
import { Route as FinanceImportFeesRouteImport } from './routes/finance.import-fees'
import { Route as StudentsIdIndexRouteImport } from './routes/students.$id.index'
import { Route as StudentsIdPrintRouteImport } from './routes/students.$id.print'
import { Route as StudentsIdEditRouteImport } from './routes/students.$id.edit'
import { Route as GradesIdPrintRouteImport } from './routes/grades.$id.print'
import { Route as ClassesIdPrintRouteImport } from './routes/classes.$id.print'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsNewRoute = ReceiptsNewRouteImport.update({
  id: '/receipts/new',
  path: '/receipts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReceiptUploadRoute = FinanceReceiptUploadRouteImport.update({
  id: '/finance/receipt-upload',
  path: '/finance/receipt-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInstallmentsRoute = FinanceInstallmentsRouteImport.update({
  id: '/finance/installments',
  path: '/finance/installments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceImportFeesRoute = FinanceImportFeesRouteImport.update({
  id: '/finance/import-fees',
  path: '/finance/import-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdIndexRoute = StudentsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsIdRoute,
} as any)
const StudentsIdPrintRoute = StudentsIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => StudentsIdRoute,
} as any)
const StudentsIdEditRoute = StudentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StudentsIdRoute,
} as any)
const GradesIdPrintRoute = GradesIdPrintRouteImport.update({
  id: '/grades/$id/print',
  path: '/grades/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIdPrintRoute = ClassesIdPrintRouteImport.update({
  id: '/classes/$id/print',
  path: '/classes/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance/import-fees': typeof FinanceImportFeesRoute
  '/finance/installments': typeof FinanceInstallmentsRoute
  '/finance/receipt-upload': typeof FinanceReceiptUploadRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/students/$id': typeof StudentsIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/activity/': typeof ActivityIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/classes/$id/print': typeof ClassesIdPrintRoute
  '/grades/$id/print': typeof GradesIdPrintRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
  '/students/$id/print': typeof StudentsIdPrintRoute
  '/students/$id/': typeof StudentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance/import-fees': typeof FinanceImportFeesRoute
  '/finance/installments': typeof FinanceInstallmentsRoute
  '/finance/receipt-upload': typeof FinanceReceiptUploadRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/students/new': typeof StudentsNewRoute
  '/activity': typeof ActivityIndexRoute
  '/admin': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
  '/imports': typeof ImportsIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/classes/$id/print': typeof ClassesIdPrintRoute
  '/grades/$id/print': typeof GradesIdPrintRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
  '/students/$id/print': typeof StudentsIdPrintRoute
  '/students/$id': typeof StudentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/finance/import-fees': typeof FinanceImportFeesRoute
  '/finance/installments': typeof FinanceInstallmentsRoute
  '/finance/receipt-upload': typeof FinanceReceiptUploadRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/students/$id': typeof StudentsIdRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/activity/': typeof ActivityIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/classes/$id/print': typeof ClassesIdPrintRoute
  '/grades/$id/print': typeof GradesIdPrintRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
  '/students/$id/print': typeof StudentsIdPrintRoute
  '/students/$id/': typeof StudentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/finance/import-fees'
    | '/finance/installments'
    | '/finance/receipt-upload'
    | '/receipts/new'
    | '/students/$id'
    | '/students/new'
    | '/activity/'
    | '/admin/'
    | '/archive/'
    | '/imports/'
    | '/receipts/'
    | '/students/'
    | '/transfers/'
    | '/classes/$id/print'
    | '/grades/$id/print'
    | '/students/$id/edit'
    | '/students/$id/print'
    | '/students/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/finance/import-fees'
    | '/finance/installments'
    | '/finance/receipt-upload'
    | '/receipts/new'
    | '/students/new'
    | '/activity'
    | '/admin'
    | '/archive'
    | '/imports'
    | '/receipts'
    | '/students'
    | '/transfers'
    | '/classes/$id/print'
    | '/grades/$id/print'
    | '/students/$id/edit'
    | '/students/$id/print'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/finance/import-fees'
    | '/finance/installments'
    | '/finance/receipt-upload'
    | '/receipts/new'
    | '/students/$id'
    | '/students/new'
    | '/activity/'
    | '/admin/'
    | '/archive/'
    | '/imports/'
    | '/receipts/'
    | '/students/'
    | '/transfers/'
    | '/classes/$id/print'
    | '/grades/$id/print'
    | '/students/$id/edit'
    | '/students/$id/print'
    | '/students/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FinanceImportFeesRoute: typeof FinanceImportFeesRoute
  FinanceInstallmentsRoute: typeof FinanceInstallmentsRoute
  FinanceReceiptUploadRoute: typeof FinanceReceiptUploadRoute
  ReceiptsNewRoute: typeof ReceiptsNewRoute
  StudentsIdRoute: typeof StudentsIdRouteWithChildren
  StudentsNewRoute: typeof StudentsNewRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  ImportsIndexRoute: typeof ImportsIndexRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
  ClassesIdPrintRoute: typeof ClassesIdPrintRoute
  GradesIdPrintRoute: typeof GradesIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/': {
      id: '/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/new': {
      id: '/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/new': {
      id: '/receipts/new'
      path: '/receipts/new'
      fullPath: '/receipts/new'
      preLoaderRoute: typeof ReceiptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/receipt-upload': {
      id: '/finance/receipt-upload'
      path: '/finance/receipt-upload'
      fullPath: '/finance/receipt-upload'
      preLoaderRoute: typeof FinanceReceiptUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/installments': {
      id: '/finance/installments'
      path: '/finance/installments'
      fullPath: '/finance/installments'
      preLoaderRoute: typeof FinanceInstallmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/import-fees': {
      id: '/finance/import-fees'
      path: '/finance/import-fees'
      fullPath: '/finance/import-fees'
      preLoaderRoute: typeof FinanceImportFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id/': {
      id: '/students/$id/'
      path: '/'
      fullPath: '/students/$id/'
      preLoaderRoute: typeof StudentsIdIndexRouteImport
      parentRoute: typeof StudentsIdRoute
    }
    '/students/$id/print': {
      id: '/students/$id/print'
      path: '/print'
      fullPath: '/students/$id/print'
      preLoaderRoute: typeof StudentsIdPrintRouteImport
      parentRoute: typeof StudentsIdRoute
    }
    '/students/$id/edit': {
      id: '/students/$id/edit'
      path: '/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof StudentsIdEditRouteImport
      parentRoute: typeof StudentsIdRoute
    }
    '/grades/$id/print': {
      id: '/grades/$id/print'
      path: '/grades/$id/print'
      fullPath: '/grades/$id/print'
      preLoaderRoute: typeof GradesIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$id/print': {
      id: '/classes/$id/print'
      path: '/classes/$id/print'
      fullPath: '/classes/$id/print'
      preLoaderRoute: typeof ClassesIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentsIdRouteChildren {
  StudentsIdEditRoute: typeof StudentsIdEditRoute
  StudentsIdPrintRoute: typeof StudentsIdPrintRoute
  StudentsIdIndexRoute: typeof StudentsIdIndexRoute
}

const StudentsIdRouteChildren: StudentsIdRouteChildren = {
  StudentsIdEditRoute: StudentsIdEditRoute,
  StudentsIdPrintRoute: StudentsIdPrintRoute,
  StudentsIdIndexRoute: StudentsIdIndexRoute,
}

const StudentsIdRouteWithChildren = StudentsIdRoute._addFileChildren(
  StudentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FinanceImportFeesRoute: FinanceImportFeesRoute,
  FinanceInstallmentsRoute: FinanceInstallmentsRoute,
  FinanceReceiptUploadRoute: FinanceReceiptUploadRoute,
  ReceiptsNewRoute: ReceiptsNewRoute,
  StudentsIdRoute: StudentsIdRouteWithChildren,
  StudentsNewRoute: StudentsNewRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  ImportsIndexRoute: ImportsIndexRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  TransfersIndexRoute: TransfersIndexRoute,
  ClassesIdPrintRoute: ClassesIdPrintRoute,
  GradesIdPrintRoute: GradesIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
